### PR TITLE
Quickfix for pgBouncer

### PR DESCRIPTION
**Pull request by ostcar**

### CODE REVIEW

**Comment by ostcar** [comment]
@peb-adr Could you confirm by testing it again or by looking at the code that this will solve the problem?

**Review by peb-adr — APPROVED** [review]

**Comment by peb-adr** [comment]
@ostcar are you here? you know why the tests are failing now?

**Comment by peb-adr** [comment]
ok nvm restarted tests and they passed..

**Comment by ostcar** [comment]
Yes. It is a test that has an internal timeout. It sometimes succeeds and sometimes fails. (it only fails on GitHub).

I already tried to fix this be using a much higher timeout. But it keeps falling.

It helps to rerun the tests. But of cause I have to rewrite it somehow.

**Pull request merged**
